# Generated by Django 5.0.6 on 2024-06-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_github_link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='project_tools',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_description',
            field=models.TextField(),
        ),
    ]
