# Generated by Django 5.0.6 on 2024-06-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_user_favorite_favorites_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='search_reference',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
