# Generated by Django 5.0.6 on 2024-06-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_projects_search_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_image',
            field=models.ImageField(default=None, null=True, upload_to='./main/static/img/project_img'),
        ),
    ]
