# Generated by Django 5.0.6 on 2024-07-14 14:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user_uiid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_UIID',
            new_name='User_UUID',
        ),
    ]
